"""empty message

Revision ID: 7e077ea0b7c7
Revises: 2ecd4039e9df
Create Date: 2025-06-26 22:42:00.142526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e077ea0b7c7'
down_revision = '2ecd4039e9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_id')
        batch_op.drop_index('idx_post_id')
        batch_op.drop_index('idx_user_id')
        batch_op.create_index('idx_like_comment_id', ['comment_id'], unique=False)
        batch_op.create_index('idx_like_post_id', ['post_id'], unique=False)
        batch_op.create_index('idx_like_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index('idx_difficulty_level')
        batch_op.create_index('idx_route_difficulty_level', ['difficulty_level'], unique=False)
        batch_op.create_index('idx_route_post_id', ['post_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_image_url')

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index('idx_route_post_id')
        batch_op.drop_index('idx_route_difficulty_level')
        batch_op.create_index('idx_difficulty_level', ['difficulty_level'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('idx_like_user_id')
        batch_op.drop_index('idx_like_post_id')
        batch_op.drop_index('idx_like_comment_id')
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_post_id', ['post_id'], unique=False)
        batch_op.create_index('idx_comment_id', ['comment_id'], unique=False)

    # ### end Alembic commands ###
